/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GestorRouteImport } from './routes/_gestor'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as GestorAgendaRouteImport } from './routes/_gestor/agenda'
import { Route as GestorCatalogoRouteImport } from './routes/_gestor/catalogo'
import { Route as GestorConfiguracoesRouteImport } from './routes/_gestor/configuracoes'
import { Route as GestorCredenciaisRouteImport } from './routes/_gestor/credenciais'
import { Route as GestorGestaoRouteImport } from './routes/_gestor/gestao'
import { Route as GestorHojeRouteImport } from './routes/_gestor/hoje'
import { Route as GestorNotificacoesRouteImport } from './routes/_gestor/notificacoes'
import { Route as AtendimentoSessionIdRouteImport } from './routes/atendimento.$sessionId'
import { Route as AtendimentoNovoRouteImport } from './routes/atendimento.novo'
import { Route as ClienteIndexRouteImport } from './routes/cliente/index'
import { Route as ClienteAgendaRouteImport } from './routes/cliente/agenda'
import { Route as ClienteEvolucaoRouteImport } from './routes/cliente/evolucao'
import { Route as ClientePerfilRouteImport } from './routes/cliente/perfil'
import { Route as GestorAtendimentosAppointmentIdRouteImport } from './routes/_gestor/atendimentos.$appointmentId'
import { Route as GestorClientesIndexRouteImport } from './routes/_gestor/clientes/index'
import { Route as GestorClientesClientIdRouteImport } from './routes/_gestor/clientes/$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorRoute = GestorRouteImport.update({
  id: '/_gestor',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorAgendaRoute = GestorAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => GestorRoute,
} as any)
const GestorCatalogoRoute = GestorCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => GestorRoute,
} as any)
const GestorConfiguracoesRoute = GestorConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => GestorRoute,
} as any)
const GestorCredenciaisRoute = GestorCredenciaisRouteImport.update({
  id: '/credenciais',
  path: '/credenciais',
  getParentRoute: () => GestorRoute,
} as any)
const GestorGestaoRoute = GestorGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => GestorRoute,
} as any)
const GestorHojeRoute = GestorHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => GestorRoute,
} as any)
const GestorNotificacoesRoute = GestorNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => GestorRoute,
} as any)
const AtendimentoSessionIdRoute = AtendimentoSessionIdRouteImport.update({
  id: '/atendimento/$sessionId',
  path: '/atendimento/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoNovoRoute = AtendimentoNovoRouteImport.update({
  id: '/atendimento/novo',
  path: '/atendimento/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteAgendaRoute = ClienteAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteEvolucaoRoute = ClienteEvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePerfilRoute = ClientePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ClienteRoute,
} as any)
const GestorAtendimentosAppointmentIdRoute =
  GestorAtendimentosAppointmentIdRouteImport.update({
    id: '/atendimentos/$appointmentId',
    path: '/atendimentos/$appointmentId',
    getParentRoute: () => GestorRoute,
  } as any)
const GestorClientesIndexRoute = GestorClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => GestorRoute,
} as any)
const GestorClientesClientIdRoute = GestorClientesClientIdRouteImport.update({
  id: '/clientes/$clientId',
  path: '/clientes/$clientId',
  getParentRoute: () => GestorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/agenda': typeof GestorAgendaRoute
  '/catalogo': typeof GestorCatalogoRoute
  '/configuracoes': typeof GestorConfiguracoesRoute
  '/credenciais': typeof GestorCredenciaisRoute
  '/gestao': typeof GestorGestaoRoute
  '/hoje': typeof GestorHojeRoute
  '/notificacoes': typeof GestorNotificacoesRoute
  '/atendimento/$sessionId': typeof AtendimentoSessionIdRoute
  '/atendimento/novo': typeof AtendimentoNovoRoute
  '/cliente/agenda': typeof ClienteAgendaRoute
  '/cliente/evolucao': typeof ClienteEvolucaoRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/': typeof ClienteIndexRoute
  '/atendimentos/$appointmentId': typeof GestorAtendimentosAppointmentIdRoute
  '/clientes/$clientId': typeof GestorClientesClientIdRoute
  '/clientes/': typeof GestorClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/agenda': typeof GestorAgendaRoute
  '/catalogo': typeof GestorCatalogoRoute
  '/configuracoes': typeof GestorConfiguracoesRoute
  '/credenciais': typeof GestorCredenciaisRoute
  '/gestao': typeof GestorGestaoRoute
  '/hoje': typeof GestorHojeRoute
  '/notificacoes': typeof GestorNotificacoesRoute
  '/atendimento/$sessionId': typeof AtendimentoSessionIdRoute
  '/atendimento/novo': typeof AtendimentoNovoRoute
  '/cliente/agenda': typeof ClienteAgendaRoute
  '/cliente/evolucao': typeof ClienteEvolucaoRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente': typeof ClienteIndexRoute
  '/atendimentos/$appointmentId': typeof GestorAtendimentosAppointmentIdRoute
  '/clientes/$clientId': typeof GestorClientesClientIdRoute
  '/clientes': typeof GestorClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_gestor': typeof GestorRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_gestor/agenda': typeof GestorAgendaRoute
  '/_gestor/catalogo': typeof GestorCatalogoRoute
  '/_gestor/configuracoes': typeof GestorConfiguracoesRoute
  '/_gestor/credenciais': typeof GestorCredenciaisRoute
  '/_gestor/gestao': typeof GestorGestaoRoute
  '/_gestor/hoje': typeof GestorHojeRoute
  '/_gestor/notificacoes': typeof GestorNotificacoesRoute
  '/atendimento/$sessionId': typeof AtendimentoSessionIdRoute
  '/atendimento/novo': typeof AtendimentoNovoRoute
  '/cliente/agenda': typeof ClienteAgendaRoute
  '/cliente/evolucao': typeof ClienteEvolucaoRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/': typeof ClienteIndexRoute
  '/_gestor/atendimentos/$appointmentId': typeof GestorAtendimentosAppointmentIdRoute
  '/_gestor/clientes/$clientId': typeof GestorClientesClientIdRoute
  '/_gestor/clientes/': typeof GestorClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cliente'
    | '/redefinir-senha'
    | '/agenda'
    | '/catalogo'
    | '/configuracoes'
    | '/credenciais'
    | '/gestao'
    | '/hoje'
    | '/notificacoes'
    | '/atendimento/$sessionId'
    | '/atendimento/novo'
    | '/cliente/agenda'
    | '/cliente/evolucao'
    | '/cliente/perfil'
    | '/cliente/'
    | '/atendimentos/$appointmentId'
    | '/clientes/$clientId'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/redefinir-senha'
    | '/agenda'
    | '/catalogo'
    | '/configuracoes'
    | '/credenciais'
    | '/gestao'
    | '/hoje'
    | '/notificacoes'
    | '/atendimento/$sessionId'
    | '/atendimento/novo'
    | '/cliente/agenda'
    | '/cliente/evolucao'
    | '/cliente/perfil'
    | '/cliente'
    | '/atendimentos/$appointmentId'
    | '/clientes/$clientId'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/_gestor'
    | '/cliente'
    | '/redefinir-senha'
    | '/_gestor/agenda'
    | '/_gestor/catalogo'
    | '/_gestor/configuracoes'
    | '/_gestor/credenciais'
    | '/_gestor/gestao'
    | '/_gestor/hoje'
    | '/_gestor/notificacoes'
    | '/atendimento/$sessionId'
    | '/atendimento/novo'
    | '/cliente/agenda'
    | '/cliente/evolucao'
    | '/cliente/perfil'
    | '/cliente/'
    | '/_gestor/atendimentos/$appointmentId'
    | '/_gestor/clientes/$clientId'
    | '/_gestor/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GestorRoute: typeof GestorRouteWithChildren
  ClienteRoute: typeof ClienteRouteWithChildren
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  AtendimentoSessionIdRoute: typeof AtendimentoSessionIdRoute
  AtendimentoNovoRoute: typeof AtendimentoNovoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gestor': {
      id: '/_gestor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gestor/agenda': {
      id: '/_gestor/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof GestorAgendaRouteImport
      parentRoute: typeof GestorRoute
    }
    '/_gestor/catalogo': {
      id: '/_gestor/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof GestorCatalogoRouteImport
      parentRoute: typeof GestorRoute
    }
    '/_gestor/configuracoes': {
      id: '/_gestor/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof GestorConfiguracoesRouteImport
      parentRoute: typeof GestorRoute
    }
    '/_gestor/credenciais': {
      id: '/_gestor/credenciais'
      path: '/credenciais'
      fullPath: '/credenciais'
      preLoaderRoute: typeof GestorCredenciaisRouteImport
      parentRoute: typeof GestorRoute
    }
    '/_gestor/gestao': {
      id: '/_gestor/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestorGestaoRouteImport
      parentRoute: typeof GestorRoute
    }
    '/_gestor/hoje': {
      id: '/_gestor/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof GestorHojeRouteImport
      parentRoute: typeof GestorRoute
    }
    '/_gestor/notificacoes': {
      id: '/_gestor/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof GestorNotificacoesRouteImport
      parentRoute: typeof GestorRoute
    }
    '/atendimento/$sessionId': {
      id: '/atendimento/$sessionId'
      path: '/atendimento/$sessionId'
      fullPath: '/atendimento/$sessionId'
      preLoaderRoute: typeof AtendimentoSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento/novo': {
      id: '/atendimento/novo'
      path: '/atendimento/novo'
      fullPath: '/atendimento/novo'
      preLoaderRoute: typeof AtendimentoNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/agenda': {
      id: '/cliente/agenda'
      path: '/agenda'
      fullPath: '/cliente/agenda'
      preLoaderRoute: typeof ClienteAgendaRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/evolucao': {
      id: '/cliente/evolucao'
      path: '/evolucao'
      fullPath: '/cliente/evolucao'
      preLoaderRoute: typeof ClienteEvolucaoRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/perfil': {
      id: '/cliente/perfil'
      path: '/perfil'
      fullPath: '/cliente/perfil'
      preLoaderRoute: typeof ClientePerfilRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/_gestor/atendimentos/$appointmentId': {
      id: '/_gestor/atendimentos/$appointmentId'
      path: '/atendimentos/$appointmentId'
      fullPath: '/atendimentos/$appointmentId'
      preLoaderRoute: typeof GestorAtendimentosAppointmentIdRouteImport
      parentRoute: typeof GestorRoute
    }
    '/_gestor/clientes/': {
      id: '/_gestor/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof GestorClientesIndexRouteImport
      parentRoute: typeof GestorRoute
    }
    '/_gestor/clientes/$clientId': {
      id: '/_gestor/clientes/$clientId'
      path: '/clientes/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof GestorClientesClientIdRouteImport
      parentRoute: typeof GestorRoute
    }
  }
}

interface GestorRouteChildren {
  GestorAgendaRoute: typeof GestorAgendaRoute
  GestorCatalogoRoute: typeof GestorCatalogoRoute
  GestorConfiguracoesRoute: typeof GestorConfiguracoesRoute
  GestorCredenciaisRoute: typeof GestorCredenciaisRoute
  GestorGestaoRoute: typeof GestorGestaoRoute
  GestorHojeRoute: typeof GestorHojeRoute
  GestorNotificacoesRoute: typeof GestorNotificacoesRoute
  GestorAtendimentosAppointmentIdRoute: typeof GestorAtendimentosAppointmentIdRoute
  GestorClientesClientIdRoute: typeof GestorClientesClientIdRoute
  GestorClientesIndexRoute: typeof GestorClientesIndexRoute
}

const GestorRouteChildren: GestorRouteChildren = {
  GestorAgendaRoute: GestorAgendaRoute,
  GestorCatalogoRoute: GestorCatalogoRoute,
  GestorConfiguracoesRoute: GestorConfiguracoesRoute,
  GestorCredenciaisRoute: GestorCredenciaisRoute,
  GestorGestaoRoute: GestorGestaoRoute,
  GestorHojeRoute: GestorHojeRoute,
  GestorNotificacoesRoute: GestorNotificacoesRoute,
  GestorAtendimentosAppointmentIdRoute: GestorAtendimentosAppointmentIdRoute,
  GestorClientesClientIdRoute: GestorClientesClientIdRoute,
  GestorClientesIndexRoute: GestorClientesIndexRoute,
}

const GestorRouteWithChildren =
  GestorRoute._addFileChildren(GestorRouteChildren)

interface ClienteRouteChildren {
  ClienteAgendaRoute: typeof ClienteAgendaRoute
  ClienteEvolucaoRoute: typeof ClienteEvolucaoRoute
  ClientePerfilRoute: typeof ClientePerfilRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteAgendaRoute: ClienteAgendaRoute,
  ClienteEvolucaoRoute: ClienteEvolucaoRoute,
  ClientePerfilRoute: ClientePerfilRoute,
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GestorRoute: GestorRouteWithChildren,
  ClienteRoute: ClienteRouteWithChildren,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  AtendimentoSessionIdRoute: AtendimentoSessionIdRoute,
  AtendimentoNovoRoute: AtendimentoNovoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
